### ISSUE TITLE
关于小波变换和图卷积

### ISSUE THREAD

**Issue by Wangbiao2** [xyl-507/SmallTrack#2]
大佬，非常感谢您的工作。我想问一下加入小波变换后的resnet50您是在imagenet上做过预训练吗？另外，分类响应图后接gnn我实验发现收敛速度明显变慢了，您训练时也是这样的吗？多谢您回复

**Comment by xyl-507** [comment]
@Wangbiao2 
感谢您对我们工作的关注。
我们的backbone没有在imagenet上预训练，直接使用的是pysot提供的预训练模型即可。
在训练过程中，gnn会占用一定的训练时间，所以速度会慢点，但实际推理时速度影响不大。
